- PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
Should be "0 occurrences were", not "0 occurrence was".
> Fix plurals in find-replace dialog.

- readme.md
Simply added hyperlinks in a few places in the readme. The main motivation for this was that finding the download link for the old version of Boost wasn't as straight forward as it could have been.
> [DOCS] add readme hyperlinks

- PowerEditor/src/Notepad_plus_Window.cpp
Passing -notabbar changes the settings. I would expect command-line arguments to only affect one session of the program.
There are a couple of ways of solving this, but to keep NPPM_HIDETABBAR backwards compatible I chose to restore the setting in the init function it is changed.
http://sourceforge.net/p/notepad-plus/bugs/5274/
> When hiding tab bar via command-line parameter, don't affect settings.

- PowerEditor/src/WinControls/Preference/preferenceDlg.cpp
This patch fixes an issue with the file status auto-detection settings.
If you uncheck and then check the "Enable" check box under "File Status Auto-Detection" in preferences, "Update silently" is displayed unchecked, but files are actually updated silently.
This patch also makes the "Update silently" and "Scroll to the last line" values retained when you disable/enable status auto-detection.
http://sourceforge.net/p/notepad-plus/patches/661/
> Fix file status auto-detection settings

- PowerEditor/src/Notepad_plus.cpp
go to next indicator (goToNextIndicator) doesn't work when  only one character is selected. It's a classical problem of number of pole and number of interval.
The function go to previous indicatior (goToPreviousIndicator) works fine in those conditions.
> go to next indicator broken with only one char

- PowerEditor/src/MISC/Common/Common.cpp
- PowerEditor/src/MISC/Common/Common.h
- PowerEditor/src/NppCommands.cpp
- PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp
- PowerEditor/src/ScitillaComponent/ScintillaEditView.h
Some more fixes for yesterday's sort optimization PR.
Most commits should be self-explanatory.
6e84be2 fixes a bug where the sort would insert newline at the wrong place unless the entire file was sorted. To test, create a file like this:
```
1
2
3
```
Select the first two lines and sort in ascending fashion. Using yesterday's code, the file would end up like this (note that first line is an empty line):
```
1
2
3
```
But obviously 1-2 is already in ascending order and the file should have been left untouched.
> Fix things related to sort optimization

- PowerEditor/src/langs.model.xml
.jsm is short for Javascript module and is at least used in Mozilla Addons for shared Javascript code.
By the way, perhaps you could get rid of this `encoding="Windows-1252"` at the beginning. UTF-8 is the way to go :)
_____________________
Off-Topic: Maybe it would be better if you create a notepad-plus-plus organisation. After all, I suppose it's likely that it won't end with just one repository, and with an organisation there is a better overview over all repos related to a project. For instance, you could publish the website, so people could help with the translations easier. [It's also possible to transfer repositories, and GitHub redirects from the old location to the new one so that's not a problem either].
> Add jsm to the Javascript extensions

- PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.cpp
- PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.h
This struct appears to be an exact copy of Windows' OPENFILENAME struct. I don't see the point and it seems like it could cause all manner of strange issues if someone changed the NPP struct by accident.
> Remove OPENFILENAMENPP structure

- PowerEditor/src/ScitillaComponent/Buffer.cpp
The non-default constructor of the class Buffer calls the inner method
`checkFileState()`, using the private variable `_currentStatus` to determine
whether some checks on the file attached to the buffer are required or not.
However this variable is properly initialized _after_.
> ScitillaComponent: Buffer: _currentStatus is used uninitialized in ctor

- PowerEditor/src/MISC/Common/LongRunningOperation.cpp
- PowerEditor/src/MISC/Common/LongRunningOperation.h
- PowerEditor/src/NppCommands.cpp
- PowerEditor/src/ScitillaComponent/Buffer.cpp
- PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
- PowerEditor/visual.net/notepadPlus.vcxproj
1. Create a file with 100 000 GUIDs (any large file will do, really).
2. Open the file in Notepad++ and enable session snapshot.
3. Set backup time to 1 second.
4. Replace every "a" with "b" in the file.
5. Observe corruption (the CR/LFs):
FileManager::backupCurrentBuffer() guards against being called at the same time from different threads, but it does nothing to prevent non-threadsafe access to Scintilla etc. 
In an ideal world, this feature would be turned off until it can be implemented safely (it looks like a lot of work to me, but maybe someone can think of an easy solution). I don't think that's going to happen, so as a *temporary* fix I've added a mutex which will prevent corruption in *some* cases (undo, redo, replace, sort).
> Prevent file corruption in some cases

- PowerEditor/src/WinControls/DocumentMap/documentMap.cpp
- PowerEditor/src/WinControls/DocumentMap/documentMap.h
The real problem is `_viewZoneCanvas`, which can be used unitialized by `drawZone`.
> documentmap: ViewZoneDlg: fixed uninitialized variables

- .gitignore
To have a clean repository after a simple compilation
> ignore scintilla generated files

- PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
- PowerEditor/src/ScitillaComponent/FindReplaceDlg.h
It has to be __stdcall.
Remove unnecessary casts.
> Fix incorrect thread procedure prototype.

- PowerEditor/src/ScitillaComponent/Buffer.cpp
Fixed extra space between UNTITLED_STR and document number when creating a new document through the function FileManager::newEmptyDocument()
> Fixed extra space when creating a new document

- PowerEditor/src/ScitillaComponent/Buffer.cpp
- PowerEditor/src/ScitillaComponent/Buffer.h
The method `FileManager::loadFileData` uses a stack-based buffer for reading
a file. However, due to the optimization used by `Utf8_16_Read` (`UnicodeConvertor`),
this buffer is not copied, but a pointer to this object is kept.
After `loadFileData`, this object is destroyed, but is used afterward
(via `UnicodeConvertor.getNewBuf`).
This patch actually follows #145 but they are independant
> scintilla: buffer: fixed invalid read in the stack when loading a file

- PowerEditor/src/ScitillaComponent/Buffer.cpp
- PowerEditor/src/ScitillaComponent/Buffer.h
- PowerEditor/src/Utf8_16.cpp
- PowerEditor/src/Utf8_16.h
When loading a file via `FileManager::loadFileData`, a fixed-length buffer
is filled via `fread`. Then, in some cases, a conversion is done with the help
of `Utf8_16_Read`. However, the method `Utf8_16_Read::convert` performs a call
to `strlen` on this buffer. This is obviously wrong: `\0` char should be
accepted (even if a bit strange) and the buffer is not zero-terminated.
The changes merely consist in adding an additional parameter `length` to
not have to guess the size of the buffer.
The attached screenshot shows before and after the patch. The variable `length`
actually shows the good value, whereas `lengthWithStrlen` shows the previous
computed value.
> scintilla: buffer: fixed invalid read via strlen when loading a file

- PowerEditor/src/Parameters.cpp
When I was analyzing each step via the debugger, I've found a minor memory leak
when the parameters are saved.
The XML node was obviously not destroyed. However, since it occurs when quitting the application
(AFAIK), this memory leak should not even be visible by the user.
> fixed minor memory leak when exporting the parameters to XML

- PowerEditor/src/MISC/Common/precompiledHeaders.h
- PowerEditor/visual.net/notepadPlus.vs2015.vcxproj
Add missing files.
Add warning 4091 to be ignored.
Define _CRT_NON_CONFORMING_WCSTOK globally.
> Fix VS2015 compilation

- PowerEditor/visual.net/notepadPlus.vs2015.vcxproj
Commit 9ad71107e98149dc3e3e628e839d79f042437eca added file references to the new Mutex files in the VS2013 project file. To resolve build errors, these references also need to be added to the VS2015 project.
> Add missing Mutex files to VS2015 project :)

- PowerEditor/installer/APIs/php.xml
Fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/279
> Add "php" string to PHP auto-complete

- PowerEditor/src/Notepad_plus.cpp
Possible fix for https://github.com/notepad-plus-plus/notepad-plus-plus/issues/257
Needs testing. Someone that can compile Npp, please test this!
> Add CSS to languages that are auto-indented

- CONTRIBUTING.md
- PowerEditor/bin/change.log
- PowerEditor/installer/nativeLang/bengali.xml
- PowerEditor/installer/nativeLang/german.xml
- PowerEditor/installer/nativeLang/polish.xml
- PowerEditor/installer/nppSetup.nsi
- PowerEditor/installer/packageAll.bat
- PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h
- PowerEditor/src/Notepad_plus.cpp
- PowerEditor/src/Notepad_plus.h
- PowerEditor/src/NppCommands.cpp
- PowerEditor/src/NppNotification.cpp
- PowerEditor/src/Parameters.cpp
- PowerEditor/src/Parameters.h
- PowerEditor/src/ScitillaComponent/AutoCompletion.cpp
- PowerEditor/src/ScitillaComponent/Buffer.cpp
- PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp
- PowerEditor/src/ScitillaComponent/ScintillaEditView.h
- PowerEditor/src/ScitillaComponent/SmartHighlighter.cpp
- PowerEditor/src/ScitillaComponent/SmartHighlighter.h
- PowerEditor/src/WinControls/FunctionList/functionListPanel.cpp
- PowerEditor/src/langs.model.xml
- PowerEditor/src/resource.h
- PowerEditor/src/stylers.model.xml
- PowerEditor/visual.net/notepadPlus.vcxproj
- PowerEditor/visual.net/notepadPlus.vs2015.vcxproj
when a user creates a new file, uses user preferences
however when opening an empty file where notepad++ can't detect the line endings, it uses windows line endings
I've proposed a coupe of changes. First noticing that on construction Buffer::_format is set to the users eol preference, theres no need for a default fallback to be set.
1) FileManager::loadFileData sets *pFormat to -1 when it can't detect a line ending (empty file)
2) FileManager::loadFile and FileManager::ReloadBuffer only set the line ending of the buffer when format!=-1, thus uses the users preference
> empty files line endings

- PowerEditor/installer/nativeLang/english.xml
This is an attempt to add the complete, currently known unofficial strings to original english.xml language template. For version 6.8.8. Don Ho should review them, and make them official.
> Add 3 missing translatable items to master XML for 6.8.8

- PowerEditor/src/Notepad_plus.h
It seems markers within Scintilla are not a true/false value but rather a counter. Closes #2366
Related [SciTE bug](https://sourceforge.net/p/scintilla/bugs/1617/)
> Completely clear bookmarks when they are toggled off

- PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp
- PowerEditor/src/MISC/PluginsManager/PluginsManager.h
Currently plugins are in order of the *file* name (which is not always the same as its menu item). This sorts them based on the name that shows up in the menu.
> Sort plugin menu by plugin name

- PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp
There have been reports of the wordchar list getting unexpected characters (see #3137, #3105, #3100, [here](https://notepad-plus-plus.org/community/topic/13568/double-click-selects-into-previous-line), [here](https://notepad-plus-plus.org/community/topic/13509/sci_wordleft-and-sci_wordright-treats-sentences-as-words-in-new-file/2), [here](https://notepad-plus-plus.org/community/topic/13593/inconsistent-double-click-selection-of-quoted-text)). Though I can't say for certain this PR will fix those bugs since I can't consistently reproduce the issue. Either way this still is a potential buffer overrun that needs fixed.
Also see 71edfb2dba3fd94b9b8b642e3d7dd7c00eeed307 which fixed a very similar issue.
> Fix buffer overrun for wordchar list

- PowerEditor/src/NppNotification.cpp
The style at the position was reported has having all the higher bits set for some reason, thus when checking if it was a hotspot it was always false. For example the style at the position is reported as:
`4294967168 = 0b11111111111111111111111110000000`
However the styles are only 1 byte worth of data. I'm not sure why the higher bits are being set (possible due to using deprecated API calls) but this solves the immediate issue.
> Fix issue with clicking links in html/js/asp/php

- PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp
- PowerEditor/src/NppBigSwitch.cpp
- PowerEditor/src/NppCommands.cpp
- PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp
- PowerEditor/src/ScitillaComponent/FindReplaceDlg.h
- PowerEditor/src/ScitillaComponent/GoToLineDlg.h
- PowerEditor/src/ScitillaComponent/UserDefineDialog.h
- PowerEditor/src/ScitillaComponent/columnEditor.h
- PowerEditor/src/WinControls/ColourPicker/WordStyleDlg.cpp
- PowerEditor/src/WinControls/ColourPicker/WordStyleDlg.h
- PowerEditor/src/WinControls/DockingWnd/DockingCont.cpp
- PowerEditor/src/WinControls/FindCharsInRange/FindCharsInRange.h
- PowerEditor/src/WinControls/Grid/BabyGrid.cpp
- PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.cpp
- PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp
- PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.h
- PowerEditor/src/WinControls/ProjectPanel/TreeView.cpp
- PowerEditor/src/WinControls/SplitterContainer/SplitterContainer.cpp
- PowerEditor/src/WinControls/SplitterContainer/SplitterContainer.h
I'm a member of the [Pinguem.ru](https://pinguem.ru) competition on finding errors in open source projects. The issue was found with [PVS-Studio](https://www.viva64.com/en/pvs-studio/):
- V547 Expression '_isFloating == true' is always true. dockingcont.cpp 1080
- V547 Expression 'itemSelected == 2' is always true. treeview.cpp 504
- V560 A part of conditional expression is always true: 0xff. babygrid.cpp 711
- V746 Object slicing. An exception should be caught by reference rather than by value. filedialog.cpp 183
- V746 Object slicing. An exception should be caught by reference rather than by value. nppbigswitch.cpp 110
- V746 Object slicing. An exception should be caught by reference rather than by value. pluginsmanager.cpp 259
- V768 The enumeration constant 'inactiveText' is used as a …
> Fix static analyzer issues

- PowerEditor/installer/nppSetup.nsi
- PowerEditor/installer/nsisInclude/binariesComponents.nsh
This PR fixes below issues
1. **Localization files installation is broken in V7.5.2**
Fix: Moved "langs4Npp.nsh" just before "themes.nsh"
2. **After uninstallation, it does not remove below folders.**
C:\Program Files (x86)\Notepad++\plugins\APIs\Config
C:\Program Files (x86)\Notepad++\plugins\Config\Hunspell
Updated file "binariesComponents.nsh" to fix this issue
3. Nsis warning
Fix: Moved ```SectionSetSize ${mainSection} 4500``` right after section definition. So no more warning and it will provide rough estimated install size on component select page.
4. Even after selecting all the components installation size in control panel is less.
Fix: Write installation info in the end after completing all the operation and then calculate the size of InstalDir and write registry info.
> Improve installer

- PowerEditor/installer/themes/Bespin.xml
- PowerEditor/installer/themes/Black board.xml
- PowerEditor/installer/themes/Choco.xml
- PowerEditor/installer/themes/Deep Black.xml
- PowerEditor/installer/themes/Hello Kitty.xml
- PowerEditor/installer/themes/Mono Industrial.xml
- PowerEditor/installer/themes/Monokai.xml
- PowerEditor/installer/themes/Obsidian.xml
- PowerEditor/installer/themes/Plastic Code Wrap.xml
- PowerEditor/installer/themes/Ruby Blue.xml
- PowerEditor/installer/themes/Twilight.xml
- PowerEditor/installer/themes/Vibrant Ink.xml
- PowerEditor/installer/themes/Zenburn.xml
- PowerEditor/installer/themes/vim Dark Blue.xml
- PowerEditor/src/stylers.model.xml
Closes #3086 
Compare correct screenshot below with one from #3086. All themes support this style now as well.
> Add comment doc style to SQL lexer

- PowerEditor/installer/themes/Bespin.xml
- PowerEditor/installer/themes/Black board.xml
- PowerEditor/installer/themes/Choco.xml
- PowerEditor/installer/themes/Deep Black.xml
- PowerEditor/installer/themes/Hello Kitty.xml
- PowerEditor/installer/themes/HotFudgeSundae.xml
- PowerEditor/installer/themes/Mono Industrial.xml
- PowerEditor/installer/themes/Monokai.xml
- PowerEditor/installer/themes/MossyLawn.xml
- PowerEditor/installer/themes/Navajo.xml
- PowerEditor/installer/themes/Obsidian.xml
- PowerEditor/installer/themes/Plastic Code Wrap.xml
- PowerEditor/installer/themes/Ruby Blue.xml
- PowerEditor/installer/themes/Solarized-light.xml
- PowerEditor/installer/themes/Solarized.xml
- PowerEditor/installer/themes/Twilight.xml
- PowerEditor/installer/themes/Vibrant Ink.xml
- PowerEditor/installer/themes/Zenburn.xml
- PowerEditor/installer/themes/khaki.xml
- PowerEditor/installer/themes/vim Dark Blue.xml
- PowerEditor/src/stylers.model.xml
Closes #3305
Adds the "Q OPERATOR" style to all themes (`SCE_SQL_QOPERATOR`). The string literals are colorized the same as regular strings.
Before:
After:
> Add literal string style to SQL lexer

- PowerEditor/src/NppCommands.cpp
- PowerEditor/src/ScitillaComponent/ScintillaEditView.h
This adds the use of `SCI_TARGETWHOLEDOCUMENT` which is a bit cleaner and readable to target the entire document.
It also uses `SCI_COUNTCHARACTERS` which lets Scintilla count the characters in the specified range. This avoids a *potentially* large memory allocation/copy since currently if a user selects all the text in a large file, it has to create an entire copy of the text to count the characters. This new message lets Scintilla do it all internally
> Use SCI_TARGETWHOLEDOCUMENT and SCI_COUNTCHARACTERS

- PowerEditor/installer/themes/Deep Black.xml
- PowerEditor/installer/themes/Hello Kitty.xml
- PowerEditor/installer/themes/HotFudgeSundae.xml
- PowerEditor/installer/themes/Mono Industrial.xml
- PowerEditor/installer/themes/Monokai.xml
- PowerEditor/installer/themes/MossyLawn.xml
- PowerEditor/installer/themes/Navajo.xml
- PowerEditor/installer/themes/Obsidian.xml
- PowerEditor/installer/themes/Plastic Code Wrap.xml
- PowerEditor/installer/themes/Ruby Blue.xml
- PowerEditor/installer/themes/Solarized-light.xml
- PowerEditor/installer/themes/Solarized.xml
- PowerEditor/installer/themes/Twilight.xml
- PowerEditor/installer/themes/Vibrant Ink.xml
- PowerEditor/installer/themes/khaki.xml
- PowerEditor/src/stylers.model.xml
Closes #5698. This adds 4 new styles to each theme to support fstrings.  *Side note:* some of the themes had `STRINGEOL` set incorrectly. The ID should be 13 and not 12 (which is for `COMMENTBLOCK`)
> Add Python literal string interpolation

- PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp
Closes #5702, Closes #5677
See also: https://notepad-plus-plus.org/community/topic/17696/bug-problem-with-syntax-highlighting-not-working-on-asp-classic-scripts
> Set embedded ASP default language to VB

- PowerEditor/src/Parameters.cpp
> Assign ctrl+m as default shortcut for invoking mark dialog

- PowerEditor/src/WinControls/Grid/ShortcutMapper.cpp
- PowerEditor/src/WinControls/Grid/ShortcutMapper.h
Previously the shortcut mapper filtered the keycombo for every other type of command, but not scintilla commands.
Fix #12557
Fix #10486
__To test this PR:__
1. Open up the Shortcut Mapper.
2. Navigate to the `Scintilla commands` tab.
3. Enter the search term `Ctrl+` in the `Filter:` textbox.
4. Verify that all Scintilla commands that include `Control` in any one of their keyboard shortcut(s) (including a second or third shortcut) are shown in the grid.
> Enable shortcut mapper to filter keycombos for scintilla commands
